# Problem 1

In [10]:
# 1 - numpy kütüphanesini import edin

# 2 - 0 ile 10 arasında 5 sayıdan oluşan matris üretin

# 3 - matris'in boyutunu öğrenin

# 4 - matris'i yeniden boyutlandırın

# 5 - matris'in boyut sayısını öğrenin


In [28]:
import numpy as np
matris = np.random.randint(0, 11, size=(5))
print(matris)
print(matris.shape)
print(matris.reshape(5,1))
matris.ndim


[1 6 6 3 3]
(5,)
[[1]
 [6]
 [6]
 [3]
 [3]]


1

# Problem 2

In [12]:
# 1 - 0 ile 10 arasında bulunan tek sayılardan oluşan matris üretin

# 2 - Oluşturduğunuz matrisi parçalayın

# 3 - Parçalanmış matrisleri birleştirin


In [38]:
matris = np.arange(1,11)
tek_sayı = matris[matris%2 !=0]
# farklı bir yol
matris2 = np.arange(1,11,2)
matris,b,c = np.split(tek_sayı,[2,4])
print(f"{matris} / {b} / {c}")
yenimatris = np.concatenate((matris,b,c))
print(yenimatris)



[1 3] / [5 7] / [9]
[1 3 5 7 9]


# Problem 3

In [13]:
# 1 - 5 ile 100 arasında ikişer ikişer atlayarak rastgele 10 sayıdan oluşan matris üretin

# 2 - matris'in özelliklerini inceleyin


In [40]:
matris = np.arange(5, 101, 2)
np.random.shuffle(matris)
matris = matris[10:20].reshape(5, 2) 
print(matris)
print(matris.ndim)
print(matris.shape)
print(matris.size)
print(matris.dtype)

[[81 85]
 [13 79]
 [37 95]
 [ 9 97]
 [15 71]]
2
(5, 2)
10
int32
