# Problem 1 

In [2]:
# 1 - numpy kütüphanesini import edin
import numpy as np

# 2 - 5 elemanlı bir numpy array oluşturun
liste = np.array([1,2,3,4,5])

# 3 - Oluşturduğunuz arrayi küçükten büyüğe sıralayın.
print(np.sort(liste))

[1 2 3 4 5]


# Problem 2

In [36]:
# 1- (10,15,30,45,60) değerlerine sahip numpy dizisi oluşturunuz.
liste2 = np.array([10,15,30,45,60])


# 2- (5-15) arasındaki sayılarla numpy dizisi oluşturunuz.
list3 = np.arange(5,15)
print(list3)
 
# 3- (50-100) arasında 5'er 5'er artarak numpy dizisi oluşturunuz.
liste4 = np.arange(50,100,5)
print(liste4)

# 4- 10 elemanlı sıfırlardan oluşan bir dizi oluşturunuz.
liste5 = np.zeros(10)
print(liste5)

# 5- 10 elemanlı birlerden oluşan bir dizi oluşturunuz.
print(np.ones(10))

# 6- (0-100) arasında eşit aralıklı 5 sayı üretin.
liste6 = np.linspace(0,100,5)
print(liste6)

# 7- (10-30) arasında rastgele 5 tane tamsayı üretin.
liste7 = np.random.randint(10,30, size=5)
print(liste7)

# 8- [-1 ile 1] arasında 10 adet sayı üretin.
liste8 = np.random.uniform(-1,1, size=10)
print(liste8)

# 9- (3x5) boyutlarında (10-50) arasında rastgele bir matris oluşturunuz.
liste9 = np.random.randint(10,50, size=(3,5))
print(liste9)

# 10- Üretilen matrisin satır ve sütun sayıları toplamlarını hesaplayınız ?
print(np.sum(liste9, axis=0))
print(np.sum(liste9, axis=-1))

# 11- Üretilen matrisin en büyük, en küçük ve ortalaması nedir ?
print(f"{np.max(liste9)} {np.min(liste9)} {np.mean(liste9)}")

# 12- Üretilen matrisin en büyük değerinin indeksi kaçtır ?
print(liste9.argmax())

# 13- (10-20) arasındaki sayıları içeren dizinin ilk 3 elemanını seçiniz.
liste10 = np.random.randint(10,20 ,size=8)
print(liste10[:3])

# 14- Üretilen dizinin elemanlarını tersten yazdırın.
print(liste10[::-1])

# 15- Üretilen matrisin ilk satırını seçiniz.
print(liste9[0])

# 16- Üretilen matrisin 2.satır 3.sütundaki elemanı hangisidir ?
print(liste9[1,2])

# 17- Üretilen matrisin tüm satırlardaki ilk elemanı seçiniz.
print(liste9[:,0])

# 18- Üretilen matrisin her bir elemanının karesini alınız.
print(liste9**2)

# 19- Üretilen matris elemanlarının hangisi pozitif çift sayıdır ? Aralığı (-50,+50) arasında yapınız.
liste11 = np.random.randint(-50,50,size=(3,5))
poz_cift = liste11[(liste11 >0 ) & (liste11 % 2 == 0)]
print(poz_cift)



[ 5  6  7  8  9 10 11 12 13 14]
[50 55 60 65 70 75 80 85 90 95]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[  0.  25.  50.  75. 100.]
[29 22 12 15 16]
[-0.21314439  0.04007181 -0.37968326  0.71550572 -0.43218895  0.04952274
  0.26453662 -0.74334223  0.9694802   0.59553925]
[[49 28 13 44 10]
 [24 20 24 36 48]
 [13 14 33 23 36]]
[ 86  62  70 103  94]
[144 152 119]
49 10 27.666666666666668
0
[16 15 10]
[12 16 12 19 17 10 15 16]
[49 28 13 44 10]
24
[49 24 13]
[[2401  784  169 1936  100]
 [ 576  400  576 1296 2304]
 [ 169  196 1089  529 1296]]
[36 16 14]
