In [5]:
a = [1,2,3,4]
b = [2,3,4,5]
ab = []
for i in range(0,len(a)):
    ab.append(a[i] * b[i])
print(ab)

[2, 6, 12, 20]


In [13]:
import numpy as np
a = np.array([1,2,3,4])
b = np.array([2,3,4,5])
print(a*b)
x = np.array([1,2,3,4,5,6,7,8,9])
multi = x.reshape(3,3)
print(multi)
print(multi.shape)
print(x.shape)
print(x.ndim)
print(multi.ndim)

[ 2  6 12 20]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
(9,)
1
2


In [14]:
x = np.array([1,2,3,4,5])
y = np.array([6,7,8,9,10])
print(np.concatenate([x,y]))

[ 1  2  3  4  5  6  7  8  9 10]


In [20]:
mikasa = np.array([[1,2,3,4],[5,6,7,8]])
print(np.concatenate([mikasa,mikasa]))
print(np.concatenate([mikasa,mikasa], axis =1)) # sütün bazında birleştirme
print(np.concatenate([mikasa,mikasa], axis = 0)) # satır bazında birleştirme

[[1 2 3 4]
 [5 6 7 8]
 [1 2 3 4]
 [5 6 7 8]]
[[1 2 3 4 1 2 3 4]
 [5 6 7 8 5 6 7 8]]
[[1 2 3 4]
 [5 6 7 8]
 [1 2 3 4]
 [5 6 7 8]]


In [25]:
m = np.array([1,2,3,99,99,3,2,1])
print(np.split(m, [3,5]))


[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]


In [28]:
a,b,c = np.split(m, [3,5])
print(a)
print(b)
print(c)

[1 2 3]
[99 99]
[3 2 1]


In [44]:
print(np.arange(0,30,3)) 
print(np.zeros(5))
print(np.ones(5))
print(np.linspace(1,100,10)) # 1 ile 100 arasını 10 eşit parçaya böl
print(np.random.randint(0,10,3)) # 0 ile 10 arasında 3 sayı üret

[ 0  3  6  9 12 15 18 21 24 27]
[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]
[9 7 5]


In [30]:
n = np.arange(16).reshape(4,4)
print(np.vsplit(n, [2]))
print(np.hsplit(n, [2]))

[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]
[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]


In [48]:
a = np.random.randint(10, size= 10)
print(a)
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)

[4 9 9 5 1 2 5 7 5 8]
1
(10,)
10
int32


In [58]:
a = np.random.randint(100,size=20)
print(a)
a.sort()
print(a)


[39 20 15 34  9 31 15  1 59 40 38 81 19  8  1 17 99 79 78 71]
[ 1  1  8  9 15 15 17 19 20 31 34 38 39 40 59 71 78 79 81 99]


In [69]:
k = np.random.normal(20,5,(3,4)) # a normal distribution with a mean of 20 and a standard deviation of 5.
print(k)
print(np.sort(k, axis = 0)) # dikey eksene göre sıraladı
print(np.sort(k, axis = 1))

[[20.92694882 12.52969939 30.95136689 21.59963386]
 [21.09165091 22.07810585 32.97236364 22.87038006]
 [18.98480612 13.73038374 21.94609614 13.63985375]]
[[18.98480612 12.52969939 21.94609614 13.63985375]
 [20.92694882 13.73038374 30.95136689 21.59963386]
 [21.09165091 22.07810585 32.97236364 22.87038006]]
[[12.52969939 20.92694882 21.59963386 30.95136689]
 [21.09165091 22.07810585 22.87038006 32.97236364]
 [13.63985375 13.73038374 18.98480612 21.94609614]]


In [73]:
a = np.random.randint(100,size=10)
print(f"{a}, {a[3]}")
b = np.random.randint(100,size=(3,5))
print(f"{b}, {b[0,0]}")

[34  8 52  9 42 58  9 36 68 32], 9
[[ 4  5 40  7 71]
 [97 55 27  8 41]
 [76 58 10 86 48]], 4


In [80]:
a = np.random.randint(10, size=[5,5])
print(a)
print(a[:,0])
print(a[0,:])
print(a[0:2,0:3])

[[9 5 4 1 5]
 [3 5 5 6 2]
 [7 1 8 2 3]
 [5 4 5 1 9]
 [6 4 9 0 3]]
[9 3 7 5 6]
[9 5 4 1 5]
[[9 5 4]
 [3 5 5]]


In [90]:
alt_b = a[0:3,0:2]
print(alt_b)
alt_b[0,0] = 100
alt_b[1,1] = 200
print(alt_b)
print(a)

[[100   5]
 [  3 200]
 [  7   1]]
[[100   5]
 [  3 200]
 [  7   1]]
[[100   5   4   1   5]
 [  3 200   5   6   2]
 [  7   1   8   2   3]
 [  5   4   5   1   9]
 [  6   4   9   0   3]]


In [93]:
v = np.arange(1,30,3)
liste = [1,3,5]
print(v[liste])

[ 4 10 16]


In [96]:
v = np.array([1,2,3,4,5])
print(3 < v)
print(v[3<v])

[False False False  True  True]
[4 5]


In [103]:
v = np.array([1,2,3,4,5])
print(v*2)
print(v+10)
print(np.subtract(v,3))
print(np.add(v,2))
print(np.multiply(v,2))
print(np.divide(v,2))
print(np.power(v,2))
print(np.mod(v,5))

[ 2  4  6  8 10]
[11 12 13 14 15]
[-2 -1  0  1  2]
[3 4 5 6 7]
[ 2  4  6  8 10]
[0.5 1.  1.5 2.  2.5]
[ 1  4  9 16 25]
[1 2 3 4 0]


In [105]:
# 2x + y  = 10
# 3x + 7y =  25
a = np.array([[2,3],[1,7]])
b = np.array([10,25])
x = np.linalg.solve(a,b)
print(x)

[-0.45454545  3.63636364]
